In [1]:
from google.colab import drive
drive.mount("/gdrive", force_remount=True)

Mounted at /gdrive


In [5]:
import numpy as np
import torch
import torch.nn as nn
from sklearn.metrics import accuracy_score

# 데이터 읽기 함수
def load_dataset(file):
  data = np.loadtxt(file)
  print("DATA=",data)
  
  input_features = data[:,0:-1]
  print("X=",input_features)
  
  labels = np.reshape(data[:,-1],(4,1))
  print("Y=",labels)
 
  input_features = torch.tensor(input_features, dtype=torch.float)
  labels = torch.tensor(labels, dtype=torch.float)

  return (input_features, labels)

# 모델 평가 결과 계산을 위해 텐서를 리스트로 변환하는 함수
def tensor2list(input_tensor):
    return input_tensor.cpu().detach().numpy().tolist()

x, y = load_dataset("/gdrive/MyDrive/ML/train1014.txt")

# layer 1 가중치 초기화
# 이곳을 완성하세요.
w1=torch.randn(2,2,requires_grad=True)
b1=torch.randn(2,requires_grad=True)

print("\n[Init]\nw1 = {0}".format(tensor2list(w1)))
print("b1 = {0}".format(tensor2list(b1)))

# layer 2 가중치 초기화
# 이곳을 완성하세요.
w2=torch.randn(2,1,requires_grad=True)
b2=torch.randn(1,requires_grad=True)

print("w2 = {0}".format(tensor2list(w2)))
print("b2 = {0}\n".format(tensor2list(b2)))

# Activation 함수 설정
sigmoid = nn.Sigmoid()

# 이진분류 크로스엔트로피 비용 함수 설정 
loss_func = torch.nn.BCELoss()

# 옵티마이저 함수 (역전파 알고리즘을 수행할 함수)
optimizer = torch.optim.SGD([w1,b1,w2,b2],lr=0.2)

# 모델 학습
for epoch in range(1001):

    # H(X) 계산: forward 연산
    # 이곳을 완성하세요.
    L2=sigmoid(torch.add(torch.matmul(x,w1),b1))
    hx=sigmoid(torch.add(torch.matmul(L2,w2),b2))

    # 비용 계산
    cost = loss_func(hx, y)
    # 역전파 수행
    cost.backward()
    optimizer.step()

    # 100 에폭마다 비용 출력
    if epoch % 100 == 0:
        print(epoch, cost.item())

print("\n[Learned]\nw1 = {0}".format(tensor2list(w1)))
print("b1 = {0}".format(tensor2list(b1)))
print("w2 = {0}".format(tensor2list(w2)))
print("b2 = {0}\n".format(tensor2list(b2)))

# 모델 평가
# H(X) 계산: forward 연산
# 이곳을 완성사에요.
L2=sigmoid(torch.add(torch.matmul(x,w1),b1))
hx=sigmoid(torch.add(torch.matmul(L2,w2),b2))

logits = (hx > 0.5).float()
predicts = tensor2list(logits)
golds = tensor2list(y)

print("\nPRED=",predicts)
print("GOLD=",golds)
print("Accuracy : {0:f}".format(accuracy_score(golds, predicts)))

DATA= [[0. 0. 0.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]
X= [[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Y= [[0.]
 [1.]
 [1.]
 [0.]]

[Init]
w1 = [[2.7640631198883057, 0.6022922992706299], [-1.262378454208374, 0.17649362981319427]]
b1 = [-1.6734652519226074, -0.8052022457122803]
w2 = [[-0.4303077757358551], [-0.45867812633514404]]
b2 = [-0.014701751992106438]

0 0.7205512523651123
100 0.0746198371052742
200 6.318132363958284e-06
300 0.0
400 0.0
500 0.0
600 0.0
700 0.0
800 0.0
900 0.0
1000 0.0

[Learned]
w1 = [[135.40042114257812, 153.95968627929688], [-162.0223846435547, -196.81085205078125]]
b1 = [-117.0215072631836, 140.53656005859375]
w2 = [[175.2339630126953], [-232.0233917236328]]
b2 = [167.0394287109375]


PRED= [[0.0], [1.0], [1.0], [0.0]]
GOLD= [[0.0], [1.0], [1.0], [0.0]]
Accuracy : 1.000000
